# Random Forest Classifier

### Random forest classifier is a type of supervised machine learning algorithm. You can clearly see it from its name it creates a forest and makes it somehow random.The forest it builds is ensamble most of the time it is trained with bagging method.The general idea of the bagging method is that a combination of learning models increases the over all result.

### YOu can say that Random forest builds multiple decision trees and merges them together to get a mor accurate and stable prediction.

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Ml libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [2]:
# Import the dataset
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
df.isnull().sum()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [4]:
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype =="category":
     df[col] =le.fit_transform(df[col])
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [5]:
scaler = StandardScaler()
scaler.fit_transform(df)

array([[-3.14711305e-01, -1.43994695e+00, -1.34335316e+00, ...,
         2.79157595e-01, -6.21581561e-01, -6.00192629e-01],
       [-1.06323531e+00, -9.69205340e-01,  7.44405889e-01, ...,
         2.79157595e-01, -6.21581561e-01,  4.53382921e-01],
       [ 1.37779900e-01,  3.63355539e-01,  7.44405889e-01, ...,
         2.79157595e-01, -6.21581561e-01,  4.53382921e-01],
       ...,
       [ 3.24629502e-01, -7.22971264e-01,  7.44405889e-01, ...,
        -8.02024201e-01, -6.21581561e-01, -6.00192629e-01],
       [-2.21286504e-01, -9.04025732e-01,  7.44405889e-01, ...,
        -8.02024201e-01, -6.21581561e-01, -6.00192629e-01],
       [-1.13228903e-01,  1.24660453e-03, -1.34335316e+00, ...,
         1.36033939e+00, -6.21581561e-01, -6.00192629e-01]],
      shape=(244, 7))

In [6]:
# Split the data into X and y
X = df.drop("tip", axis =1)
y = df["tip"]

# split the X and y for model training
X_train,X_test,y_test,y_train = train_test_split(X,y, test_size=0.2, )

# call and fit the model and predict the model
model = RandomForestRegressor()
model.fit(X_train,y_train)
y_predict = model.predict(X_test)

# Evaluation of the model
print("classification_report :", classification_report(y_test,y_predict))
print("confusion_matrix :", confusion_matrix(y_test,y_predict))

ValueError: Found input variables with inconsistent numbers of samples: [195, 49]